commom: &common
  adapter: postgresql
  encoding: unicode
  username: ta6
  password: root
  host: localhost
  pool: 10
  timeout: 15000
  min_messages: warning

development:
  <<: *common
  database: BC_development

test:
  <<: *common
  database: BC_test

staging:
  <<: *common
  database: BC_staging

production:
  database: dcdo5tmcb4nijb
  port: 5432
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: ec2-34-230-149-169.compute-1.amazonaws.com
  username: udutjkzcsdnqeq
  password: 7212a1bdf4ab1f8ba91fb57db03f068b600e533626ed4028fab1cb9b354009aa
