default:
  navigation:
    - title: Cologne
      subtitle: Categories
      url: /t/cologne
      items:
        - :title: Cologne
          :url: /t/cologne/new
    - title: Photo Frames
      subtitle: Categories
      url: /t/photo_frames
      items:
        - :title: Wooden Frames
          :url: /t/photo_frames/whooden_frames
        - :title: Plastic Frames
          :url: /t/photo_frames/plastic_frames
        - :title: Collage Photo Frames
          :url: /t/photo_frames/collage_photo_frames
        - :title: Metal Photo Frames
          :url: /t/photo_frames/metal_photo_frames
        - :title: Glass Photo
          :url: /t/photo_frames/glass_frames
    - title: Artificial Plants
      subtitle: Categories
      url: /t/artificial_plants
      items:
        - :title: Artificial Flowers
          :url: /t/artificial_plants/artificial_flowers
        - :title: Artificial Plants
          :url: /t/artificial_plants/artificial_plants
        - :title: Artificial Trees
          :url: /t/artificial_plants/artificial_trees
        - :title: Succulents
          :url: /t/artificial_plants/succulents
